app/urls.py
from django.urls import path
from .views.tarefa_views import *
from .views.usuario_views import *

urlpatterns = [
    path('', cadastrar_usuario, name='cadastrar_usuario'),
    path('listar_tarefas/', listar_tarefas, name='listar_tarefas'),
    path('cadastrar_tarefa/', cadastrar_tarefa, name='cadastrar_tarefa'),
    path('editar_tarefa/<int:id>', editar_tarefa, name='editar_tarefa'),
    path('remover_tarefa/<int:id>', remover_tarefa, name='remover_tarefa'),
    path('cadastrar_usuario/', cadastrar_usuario, name='cadastrar_usuario'),
    path('logar_usuario/', logar_usuario, name='logar_usuario'),
    path('deslogar_usuario/', deslogar_usuario, name='deslogar_usuario'),
]

gerenciador_tarefas/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'))
]

app/models.py
from django.db import models
from django.contrib.auth.models import User

class Tarefa(models.Model):
    PRIORIDADE_CHOICES = [
        ("A", "Alta"),
        ("N", "Normal"),
        ("B", "Baixa"),
    ]
    titulo = models.CharField(max_length=30, null=False, blank=False)
    descricao = models.CharField(max_length=100, null=False, blank=False)
    data_expiracao = models.DateField(null=False, blank=False)
    prioridade = models.CharField(max_length=1, choices=PRIORIDADE_CHOICES, null=False, blank=False)
    usuario = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

app/forms.py
from django import forms
from .models import Tarefa
from django.forms import DateInput
from .models import *

class TarefaForm(forms.ModelForm):
    class Meta:
        model = Tarefa
        exclude = ('usuario', )
        fields = '__all__'
        widgets = {
            'data_expiracao': DateInput(attrs={'type': 'date'})
        }

app/views/tarefa_views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect
from ..forms import TarefaForm
from ..entidades.tarefa import Tarefa
from ..services import tarefa_service

@login_required()
def listar_tarefas(request):
    tarefas = tarefa_service.listar_tarefas(request.user)
    return render(request, 'tarefas/listar_tarefas.html', {"tarefas": tarefas})

@login_required()
def cadastrar_tarefa(request):
    if request.method == "POST":
        form_tarefa = TarefaForm(request.POST)
        if form_tarefa.is_valid():
            titulo = form_tarefa.cleaned_data["titulo"]
            descricao = form_tarefa.cleaned_data["descricao"]
            data_expiracao = form_tarefa.cleaned_data["data_expiracao"]
            prioridade = form_tarefa.cleaned_data["prioridade"]
            tarefa_nova = Tarefa(titulo=titulo, descricao=descricao, data_expiracao=data_expiracao,
                                 prioridade=prioridade, usuario=request.user)
            tarefa_service.cadastrar_tarefa(tarefa_nova)
            return redirect('listar_tarefas')
    else:
        form_tarefa = TarefaForm()
    return render(request, 'tarefas/form_tarefa.html', {'form_tarefa': form_tarefa})

@login_required()
def editar_tarefa(request, id):
    tarefa_bd = tarefa_service.listar_tarefa_id(id)
    if tarefa_bd.usuario != request.user:
        return HttpResponse("Não Permitido.")
    form_tarefa = TarefaForm(request.POST or None, instance=tarefa_bd)
    if form_tarefa.is_valid():
        titulo = form_tarefa.cleaned_data["titulo"]
        descricao = form_tarefa.cleaned_data["descricao"]
        data_expiracao = form_tarefa.cleaned_data["data_expiracao"]
        prioridade = form_tarefa.cleaned_data["prioridade"]
        tarefa_nova = Tarefa(titulo=titulo, descricao=descricao, data_expiracao=data_expiracao,
                             prioridade=prioridade, usuario=request.user)
        tarefa_service.editar_tarefa(tarefa_bd, tarefa_nova)
        return redirect('listar_tarefas')
    return render(request, 'tarefas/form_tarefa.html', {'form_tarefa': form_tarefa})

@login_required()
def remover_tarefa(request, id):
    tarefa_bd = tarefa_service.listar_tarefa_id(id)
    if tarefa_bd.usuario != request.user:
        return HttpResponse("Não Permitido.")
    if request.method == "POST":
        tarefa_service.remover_tarefa(tarefa_bd)
        return redirect('listar_tarefas')
    return render (request, 'tarefas/confirma_exclusao.html', {'tarefa': tarefa_bd})

app/views/usuario_views.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages


def cadastrar_usuario(request):
    if request.method == "POST":
        form_usuario = UserCreationForm(request.POST)
        if form_usuario.is_valid():
            form_usuario.save()
            return redirect('listar_tarefas')
    else:
        form_usuario = UserCreationForm()
    return render(request, 'usuarios/form_usuario.html', {"form_usuario": form_usuario})


def logar_usuario(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        usuario = authenticate(request, username=username, password=password)
        if usuario is not None:
            login(request, usuario)
            return redirect('listar_tarefas')
        else:
            messages.error(request, 'Credenciais do usuário incorretas!')
            return redirect('logar_usuario')
    else:
        form_login = AuthenticationForm()
    form_login = AuthenticationForm()
    return render(request, 'usuarios/login.html', {"form_login": form_login})

def deslogar_usuario(request):
    logout(request)
    return redirect('logar_usuario')

app/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'app/css/bootstrap.css' %}">
    <title>Gerênciador de Tarefas</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand text-white">Gerênciador de Tarefas</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'listar_tarefas' %}">Listar Tarefas</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'deslogar_usuario' %}">Sair</a>
      </li>
    </ul>
  </div>
</nav>
<main class="container">


{% block conteudo %}

{% endblock conteudo %}
</main>
<footer>
    <div class="footer-copyright text-center py-3"> 2019 developed:
    <a href="https://github.com/PauloSanches12?tab=repositories" > Paulo Sérgio</a>
  </div>
</footer>
</body>
</html>

app/templates/tarefas/confirma_exclusao.html
{% extends 'base.html' %}

{% block conteudo %}
<div class="card mb-3">
    <div class="card-header">
        <h3>Tem certeza que deseja remover a tarefa abaixo?<h3>
    </div>
    <div class="card-body">
        <h5 class="card-title"><b>Titulo:</b> {{tarefa.titulo}}</h5>
        <p class="card-text"><b>Descrição:</b> {{tarefa.descricao}}</p>
        <hr>
        <form method="post">
            {% csrf_token %}
             <button class="btn btn-outline-danger" type="submit">Remover</button>
            <a href="{% url 'listar_tarefas' %}" class="btn btn-outline-warning">Não</a>
        </form>
    </div>
</div>

{% endblock conteudo %}

app/templates/tarefas/form_tarefa.html
{% extends 'base.html' %}
{% load meus_filtros %}
{% block conteudo %}

<form method="post">
    {% csrf_token %}
    <div class="form-group">
        {{ form_tarefa.titulo.errors }}
        <label><b>Titulo:</b></label>
        {{ form_tarefa.titulo|addclass:'form-control' }}
    </div>
    <div class="form-group">
        {{ form_tarefa.descricao.errors }}
        <label><b>Descrição:</b></label>
        {{ form_tarefa.descricao|addclass:'form-control' }}
    </div>
    <div class="form-group">
        {{ form_tarefa.data_expiracao.errors }}
        <label><b>Data de Expiração:</b></label>
        {{  form_tarefa.data_expiracao|addclass:'form-control'}}
    </div>
    <div class="form-group">
        {{ form_tarefa.prioridade.errors }}
        <label><b>Prioridade:</b></label>
        {{ form_tarefa.prioridade|addclass:'form-control' }}
    </div>
    <div class="form-group">
        <input type="submit" class="btn btn-primary" value="salvar">
    </div>
</form>

{% endblock conteudo %}

app/templates/tarefas/listar_tarefas.html
{% extends 'base.html' %}

{% block conteudo %}
<h1>Listagem de Tarefas</h1>
{% for tarefa in tarefas %}
<div class="card border-primary mb-3">
    <div class="card-header bg-info  text-white">
        <b>Prioridade:</b> {{ tarefa.get_prioridade_display }}
    </div>
    <div class="card-body">
        <h5 class="card-title"><b>Titulo: </b>{{tarefa.titulo}}</h5>
        <p class="card-text"><b>Descrição: </b>{{tarefa.descricao}}</p>
        <p class="card-text"><b>Data: </b>{{tarefa.data_expiracao}}</p>
        <hr>
        <a href="{% url 'editar_tarefa' tarefa.id %}" class="text-primary">Editar Tarefa</a>
        <a href="{% url 'remover_tarefa' tarefa.id %}" class="text-danger">Remover Tarefa</a>
    </div>
</div>
{% endfor %}
<a href="{% url 'cadastrar_tarefa' %}"><input type="button" class="btn btn-primary mb-3" value="Cadastrar Tarefa"></a>
{% endblock conteudo %}

app/templates/usuarios/form_usuario.html
{% extends 'base.html' %}
{% load meus_filtros %}

{% block conteudo %}
<form method="post">
    {% csrf_token %}
    <div class="arrow">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
            <div class="card card-signin my-5">
                <div class="card-body">
                    <h5 class="card-title text-center">Cadastrar</h5>
                    <form class="form-signin">
                        <div class="form-label-group">
                            {{ form_usuario.username.errors }}
                            <label><b>Usuário:</b></label>
                            {{form_usuario.username|addclass:'form-control'}}
                        </div>
                        <div class="form-label-group">
                            {{ form_usuario.password1.errors }}
                            <label><b>Senha:</b></label>
                            {{form_usuario.password1|addclass:'form-control'}}
                        </div>
                        <br>
                        <div class="form-label-group">
                            {{ form_usuario.password2.errors }}
                            <label><b>Confirmação de Senha:</b></label>
                            {{form_usuario.password2|addclass:'form-control'}}
                        </div>
                        <br>
                        <div class="form-group">
                            <input type="submit" value="Cadastrar" class="btn btn-primary">
                            <a href="{% url 'cadastrar_tarefa' %}" class="text-primary">Já Tenho Cadastro</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</form>

{% endblock conteudo %}

app/templates/usuarios/login.html
{% extends 'base.html' %}
{% load meus_filtros %}

{% block conteudo %}


<form method="post">
    {% csrf_token %}
    {% for message in messages %}
    <div class="alert alert-danger">
        {{message}}
    </div>
    {% endfor %}
    <div class="arrow">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
            <div class="card card-signin my-5">
                <div class="card-body">
                    <h5 class="card-title text-center"><b>Sign In</b></h5>
                    <form class="form-signin">
                        <div class="form-label-group">
                            <label><b>Usuário:</b></label>
                            {{ form_login.username|addclass:'form-control'}}
                        </div>
                        <div class="form-label-group">
                            <label><b>Senha:</b></label>
                            {{ form_login.password|addclass:'form-control'}}
                        </div>
                        <br>
                        <div>
                            <input class="btn btn-lg btn-primary btn-block text-uppercase" type="submit" value="Entrar"><br>
                            <a href="{% url 'cadastrar_usuario' %}">Cadastre-se</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock conteudo %}